@extends('layouts.app')

@section('title', 'Monthly Reports')
@section('heading', 'Monthly Reports')
@section('subheading', 'Generate a downloadable summary of ' . $association->name . '\'s members\' farms, planting, damage and assistance activity for one month.')

@section('content')
<div class="grid gap-6 lg:grid-cols-3">

    <x-ui.card title="Generate a report" description="Pick the month and year to summarize." class="lg:col-span-1 h-fit">
        <form method="POST" action="{{ route('association.summaries.store') }}"
              data-confirm="Generate this monthly report using the selected information?"
              data-confirm-title="Review report parameters"
              data-confirm-action="Generate Report"
              data-confirm-review="auto"
              class="space-y-4">
            @csrf

            <div>
                <label for="month" class="mb-1.5 block text-sm font-medium text-foreground">Month</label>
                <x-ui.select name="month" :options="$months" :selected="old('month', now()->month)" />
                @error('month') <p class="mt-1 text-xs text-destructive">{{ $message }}</p> @enderror
            </div>

            <div>
                <label for="year" class="mb-1.5 block text-sm font-medium text-foreground">Year</label>
                <x-ui.select name="year" :options="$years" :selected="old('year', now()->year)" />
                @error('year') <p class="mt-1 text-xs text-destructive">{{ $message }}</p> @enderror
            </div>

            <x-ui.button type="submit" class="w-full">Generate Report</x-ui.button>
        </form>
    </x-ui.card>

    <x-ui.card title="Report history" description="Every report {{ $association->name }} has generated, most recent first." :padded="false" class="lg:col-span-2">
        <x-ui.table>
            <x-slot:head>
                <tr>
                    <th>Period</th>
                    <th>Generated by</th>
                    <th>Generated at</th>
                    <th class="text-right">Action</th>
                </tr>
            </x-slot:head>

            @forelse ($history as $entry)
                <tr>
                    <td class="font-medium text-foreground">{{ $entry->period_label }}</td>
                    <td>{{ $entry->generatedBy?->display_name ?? 'Unknown' }}</td>
                    <td>{{ $entry->generated_at->format('M j, Y g:i A') }}</td>
                    <td class="text-right">
                        <x-ui.button size="sm" variant="outline"
                            href="{{ route('association.summaries.show', ['year' => $entry->year, 'month' => $entry->month]) }}">
                            View
                        </x-ui.button>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="4" class="px-5 py-10 text-center text-sm text-muted-foreground">
                        No reports generated yet. Pick a month and year and press Generate Report.
                    </td>
                </tr>
            @endforelse
        </x-ui.table>

        @if ($history->hasPages())
            <div class="border-t border-border px-4 py-3">{{ $history->links() }}</div>
        @endif
    </x-ui.card>
</div>
@endsection
